allowBuilds:
  '@swc/core': false
  core-js: false
  unrs-resolver: false

minimumReleaseAgeExclude:
  - '@repodog/cli-cut'
  - '@repodog/cli-new'
  - '@repodog/cli-postinstall'
  - '@repodog/cli-publish'
  - '@repodog/cli-setup'
  - '@repodog/cli-utils'
  - '@repodog/cli'
  - '@repodog/commitlint-config'
  - '@repodog/eslint-config-jest'
  - '@repodog/eslint-config'
  - '@repodog/jest-config'
  - '@repodog/markdownlint-config'
  - '@repodog/prettier-config'
  - '@repodog/rollup-config'
  - '@repodog/swc-config'
  - '@repodog/syncpack-config'
  - '@repodog/ts-config'
